version: "3.9"

services:
  vue:
    build:
      context: .
    tty: true
    working_dir: /home/node/works
    volumes:
      - ./works:/home/node/works
      - exception-volumes:/home/node/works/node_modules
    ports:
      - "2222:2222"

volumes:
  exception-volumes:
